#!/usr/bin/env python3
"""Offline CoACD preprocessing for URDF collision meshes.

The browser demo only loads the generated static OBJ parts. Run this script
before publishing assets when a URDF collision mesh is not already convex.
"""

from __future__ import annotations

import argparse
import json
from pathlib import Path
import xml.etree.ElementTree as ET

import coacd
import numpy as np
import trimesh


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--urdf", required=True, type=Path, help="URDF file to scan.")
    parser.add_argument(
        "--package",
        action="append",
        default=[],
        metavar="NAME=PATH",
        help="Package map entry, e.g. franka_description=assets/urdf/franka/franka_description.",
    )
    parser.add_argument(
        "--max-parts",
        type=int,
        default=8,
        help="Maximum convex parts per source mesh.",
    )
    parser.add_argument("--threshold", type=float, default=0.05)
    parser.add_argument("--resolution", type=int, default=2000)
    parser.add_argument("--preprocess-resolution", type=int, default=50)
    parser.add_argument("--mcts-nodes", type=int, default=20)
    parser.add_argument("--mcts-iterations", type=int, default=150)
    parser.add_argument("--mcts-max-depth", type=int, default=3)
    parser.add_argument("--max-ch-vertex", type=int, default=256)
    parser.add_argument("--seed", type=int, default=0)
    parser.add_argument(
        "--force",
        action="store_true",
        help="Overwrite existing collision_coacd output directories.",
    )
    return parser.parse_args()


def parse_package_map(entries: list[str]) -> dict[str, Path]:
    package_map: dict[str, Path] = {}
    for entry in entries:
        if "=" not in entry:
            raise ValueError(f"Invalid --package entry: {entry}")
        name, path = entry.split("=", 1)
        package_map[name] = Path(path).expanduser().resolve()
    return package_map


def resolve_mesh_path(filename: str, urdf_path: Path, package_map: dict[str, Path]) -> Path:
    normalized = filename.replace("\\", "/")
    if normalized.startswith("package://"):
        package_path = normalized[len("package://") :]
        package_name, _, relative_path = package_path.partition("/")
        if package_name not in package_map:
            raise KeyError(f"No package map for {package_name}")
        return (package_map[package_name] / relative_path).resolve()
    return (urdf_path.parent / normalized).resolve()


def iter_collision_meshes(urdf_path: Path, package_map: dict[str, Path]) -> list[Path]:
    root = ET.parse(urdf_path).getroot()
    mesh_paths: list[Path] = []
    seen: set[Path] = set()
    for link in root.findall("link"):
        for collision in link.findall("collision"):
            mesh = collision.find("./geometry/mesh")
            if mesh is None:
                continue
            filename = mesh.attrib.get("filename")
            if not filename:
                continue
            path = resolve_mesh_path(filename, urdf_path, package_map)
            if path in seen:
                continue
            seen.add(path)
            mesh_paths.append(path)
    return mesh_paths


def load_mesh(path: Path) -> trimesh.Trimesh:
    loaded = trimesh.load(path, force="mesh", process=False)
    if isinstance(loaded, trimesh.Scene):
        loaded = trimesh.util.concatenate(tuple(loaded.geometry.values()))
    if not isinstance(loaded, trimesh.Trimesh):
        raise TypeError(f"Unsupported mesh type for {path}: {type(loaded)!r}")
    mesh = loaded.copy()
    mesh.remove_unreferenced_vertices()
    if mesh.faces.shape[0] == 0 or mesh.vertices.shape[0] < 4:
        raise ValueError(f"Mesh has too little geometry: {path}")
    return mesh


def export_obj(path: Path, vertices: np.ndarray, faces: np.ndarray) -> None:
    with path.open("w", encoding="utf-8") as file:
        file.write("# Generated by preprocess_urdf_coacd.py\n")
        for vertex in vertices:
            file.write(f"v {vertex[0]:.9g} {vertex[1]:.9g} {vertex[2]:.9g}\n")
        for face in faces:
            file.write(f"f {int(face[0]) + 1} {int(face[1]) + 1} {int(face[2]) + 1}\n")


def output_dir_for_mesh(mesh_path: Path) -> Path:
    if mesh_path.parent.name == "collision":
        return mesh_path.parent.parent / "collision_coacd" / mesh_path.stem
    return mesh_path.parent / f"{mesh_path.stem}_coacd"


def process_mesh(mesh_path: Path, args: argparse.Namespace) -> None:
    out_dir = output_dir_for_mesh(mesh_path)
    manifest_path = out_dir / "manifest.json"
    if manifest_path.exists() and not args.force:
        print(f"skip existing {manifest_path}")
        return

    out_dir.mkdir(parents=True, exist_ok=True)
    for old_part in out_dir.glob("part_*.obj"):
        old_part.unlink()

    mesh = load_mesh(mesh_path)
    coacd_mesh = coacd.Mesh(
        np.asarray(mesh.vertices, dtype=np.double),
        np.asarray(mesh.faces, dtype=np.int32),
    )
    parts = coacd.run_coacd(
        coacd_mesh,
        threshold=args.threshold,
        max_convex_hull=args.max_parts,
        preprocess_mode="auto",
        preprocess_resolution=args.preprocess_resolution,
        resolution=args.resolution,
        mcts_nodes=args.mcts_nodes,
        mcts_iterations=args.mcts_iterations,
        mcts_max_depth=args.mcts_max_depth,
        merge=True,
        decimate=False,
        max_ch_vertex=args.max_ch_vertex,
        seed=args.seed,
    )

    part_names: list[str] = []
    for index, (vertices, faces) in enumerate(parts[: args.max_parts]):
        part_name = f"part_{index:03d}.obj"
        export_obj(out_dir / part_name, vertices, faces)
        part_names.append(part_name)

    manifest = {
        "source": str(mesh_path),
        "parts": part_names,
        "part_count": len(part_names),
        "max_parts": args.max_parts,
        "format": "obj",
        "generator": "preprocess_urdf_coacd.py",
        "coacd": {
            "threshold": args.threshold,
            "resolution": args.resolution,
            "preprocess_resolution": args.preprocess_resolution,
            "mcts_nodes": args.mcts_nodes,
            "mcts_iterations": args.mcts_iterations,
            "mcts_max_depth": args.mcts_max_depth,
            "max_ch_vertex": args.max_ch_vertex,
            "seed": args.seed,
        },
    }
    manifest_path.write_text(json.dumps(manifest, indent=2), encoding="utf-8")
    print(f"{mesh_path.name}: {len(part_names)} parts -> {out_dir}")


def main() -> None:
    args = parse_args()
    package_map = parse_package_map(args.package)
    urdf_path = args.urdf.expanduser().resolve()
    for mesh_path in iter_collision_meshes(urdf_path, package_map):
        process_mesh(mesh_path, args)


if __name__ == "__main__":
    main()
